// MENÚ PRINCIPAL 1 PARA DESAYUNO, 2 PARA ALMUERZO Y 3 PARA SALIR.
// MENÚ DE DESAYUNO ELIGE UN NÚMERO DEL 1 AL 7 Y 8 PARA SALIR
// MENÚ DE ALMUERZO ELIGE UN NÚMERO DEL 1 AL 7 Y 8 PARA SALIR
// MENÚ OPCIONAL TIENE 2 OPCIONES: 1 PARA REGRESAR AL MENÚ PRINCIPAL Y 2 PARA SALIR. 
// MUESTRA UN MENSAJE DE DESCRIPTIVO DEL ALIMENTO ELEGIDO.
// CUANDO SE ESCRIBE OTRAS OPCIONES FUERA DE LOS NÚMEROS MENCIONADOS ARROJA UN MENSAJE DE ERROR.
// SUMA TODAS LAS CUENTAS DESDE SOLO EL DESAYUNO Y EL ALMUERZO HASTA LA CUENTA TOTAL.
funcionPrincipal();

